# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# _config.yml for Minimal Mistakes

# Site settings
title: "Winjoy Ntinyari"
email: "winjoyntinyari765@gmail.com"   
description: "Electrical and Telecommunication Engineer | Cloud & Security Aspirant"
baseurl: ""                      
url: "https://ntinyari765.github.io"  

# Author info
author:
  name: "Winjoy Ntinyari"
  avatar: "/assets/images/winjoy-ntinyari.jpg"
  bio: "Electrical and Telecommunication Engineer | Cloud & Security Aspirant"

# Minimal Mistakes theme settings
theme: minimal-mistakes-jekyll

# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Resume"
    url: /assets/files/Winjoy_Ntinyari_Resume.pdf
  - title: "Contact"
    url: /contact/

# Social links - update or add more as needed
social:
  github: ntinyari765
  linkedin: winjoyntinyari

# Plugins you may want
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults (optional)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true


